version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=/models
    deploy:
      resources:
        limits:
          memory: 6g

  streamlit:
    build: .
    container_name: alt-text-streamlit
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_API=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data:
